name: Build
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonarqube:
    name: SonarQube
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Configura Node.js (si es proyecto JS/TS)
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18  # Usa la versión de Node.js de tu proyecto

      # Instala dependencias y ejecuta tests con cobertura
      - name: Install dependencies & run tests
        run: |
          npm install
          npm test -- --coverage  # Esto genera el archivo coverage/lcov.info necesario
          # Si usas Mocha y nyc, la línea sería:
          # npx nyc --reporter=lcov mocha "test/**/*.js"

      # Escaneo con SonarQube (incluyendo tests y cobertura)
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          # Si usas SonarCloud, generalmente no necesitas SONAR_HOST_URL.
          # Si usas un SonarQube self-hosted, descomenta la línea de abajo
          # y asegúrate de que el secreto SONAR_HOST_URL esté configurado.
          # SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        with:
          args: >
            -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info